{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0e80aa7c-f7ca-4677-8d7d-57f5102e6942",
   "metadata": {},
   "outputs": [],
   "source": [
    "from PyQt6.QtCore import QPointF, QTimer, QVariantAnimation, QCoreApplication\n",
    "from PyQt6.QtGui import QColor\n",
    "from PyQt6.QtWidgets import (\n",
    "    QApplication,\n",
    "    QGraphicsItem,\n",
    "    QGraphicsView,\n",
    "    QGraphicsScene,\n",
    "    QGraphicsEllipseItem,\n",
    "    QPushButton,\n",
    ")\n",
    "import random\n",
    "from math import cos, sin, radians\n",
    "\n",
    "class Circle(QGraphicsEllipseItem):\n",
    "    def __init__(self, x, y, r, angle):\n",
    "        super().__init__(x, y, r, r)\n",
    "        self.angle = angle\n",
    "        self.diagon = random.sample(range(125, 200), 1)[0]\n",
    "        self.speed = r/100 + self.diagon/1000\n",
    "        randomcolor = random.sample(range(255), 3)\n",
    "        self.setBrush(QColor(randomcolor[0], randomcolor[1], randomcolor[2]))\n",
    "        self.animation = QVariantAnimation(duration=10)\n",
    "        self.animation.finished.connect(self.create_next_point)\n",
    "\n",
    "    def create_next_point(self):\n",
    "        if self.angle >= 360:\n",
    "            self.angle = 0\n",
    "        x = self.diagon * cos(radians(self.angle))\n",
    "        y = self.diagon * sin(radians(self.angle))\n",
    "        self.setPos(x, y)\n",
    "        self.angle += self.speed\n",
    "        self.move_to(x, y)\n",
    "\n",
    "    def move_to(self, x, y):\n",
    "        self.animation.setStartValue(self.pos())\n",
    "        self.animation.setEndValue(QPointF(x, y))\n",
    "        self.animation.start()\n",
    "\n",
    "class GraphicView(QGraphicsView):\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "        self.setWindowTitle('ИД23-1 Маслов АН')\n",
    "        button_rotateback = QPushButton(\"↺\", self)\n",
    "        button_rotateback.resize(50,50)\n",
    "        button_rotate = QPushButton(\"↻\", self)\n",
    "        button_rotate.resize(50,50)\n",
    "        button_rotate.move(50,0)\n",
    "        button_create = QPushButton(\"Новый круг\", self)\n",
    "        button_create.resize(100,50)\n",
    "        button_create.move(175,0)\n",
    "        button_speedup = QPushButton(\"↑\", self)\n",
    "        button_speedup.resize(50,50)\n",
    "        button_speedup.move(350,0)\n",
    "        button_speeddown = QPushButton(\"↓\", self)\n",
    "        button_speeddown.resize(50,50)\n",
    "        button_speeddown.move(350,50)\n",
    "        \n",
    "        scene = QGraphicsScene(self)\n",
    "        self.setScene(scene)\n",
    "        self.setSceneRect(0, 0, 400, 700)\n",
    "        circle_big = QGraphicsEllipseItem(100,400,200,200)\n",
    "        circle_big.setBrush(QColor(255, 255, 0))\n",
    "        self.scene().addItem(circle_big)\n",
    "        button_create.clicked.connect(self.create_circle)\n",
    "        button_speedup.clicked.connect(self.angle_change)\n",
    "        button_speeddown.clicked.connect(self.angle_change)\n",
    "        button_rotate.clicked.connect(self.angle_change)\n",
    "        button_rotateback.clicked.connect(self.angle_change)\n",
    "        \n",
    "    def create_circle(self):\n",
    "        angle = 270\n",
    "        x = 190\n",
    "        y = 490\n",
    "        r = random.sample(range(10, 40), 1)[0]\n",
    "        circle = Circle(x, y, r, angle)\n",
    "        circle.create_next_point()\n",
    "        self.scene().addItem(circle)\n",
    "        \n",
    "    def angle_change(self):\n",
    "        for i in self.items():\n",
    "            if i.__class__== Circle:\n",
    "                if self.sender().text() == \"↺\":\n",
    "                    i.speed = -abs(i.speed)\n",
    "                elif self.sender().text() == \"↻\":\n",
    "                    i.speed = abs(i.speed)\n",
    "                elif self.sender().text() == \"↑\":\n",
    "                    i.speed += 0.5\n",
    "                elif self.sender().text() == \"↓\":\n",
    "                    i.speed -= 0.5\n",
    "\n",
    "app = QCoreApplication.instance()\n",
    "if app is None:\n",
    "    app = QApplication([])\n",
    "    \n",
    "view = GraphicView()\n",
    "view.show()\n",
    "app.exec()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c2746fa2-fa3d-460d-8034-24f8a2dda4cc",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "548c8475-0887-4786-830c-8e412ae2b726",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "314bca7b-466b-4f61-a006-e03091b5c32b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
