version: "3.9"

services:

  api:
    build: ./app
    ports:
      - "80:8000"
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./app:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+postgresql://postgres:postgres@database:5432/FastAPIDB
    depends_on:
      - redis
      - database

  worker:
    build: ./app
    command: celery -A app.celery.tasks worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./app:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+postgresql://postgres:postgres@database:5432/FastAPIDB
    depends_on:
      - api
      - redis
      - database

  redis:
    image: redis:latest

  database:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FastAPIDB
    ports:
      - "5432:5432"
    user: postgres

volumes:
  postgres_data: