"""Fixes

Revision ID: a6a58cb84bc1
Revises: e3d498da0d28
Create Date: 2025-03-31 19:59:08.553657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a58cb84bc1'
down_revision: Union[str, None] = 'e3d498da0d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_token_key', 'users', type_='unique')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_token_key', 'users', ['token'])
    # ### end Alembic commands ###
